// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKjciSfWLxD7f9IkBq-ITqyu694dI-FE',
    appId: '1:751281066919:web:571bf20fba9287ca6f1c82',
    messagingSenderId: '751281066919',
    projectId: 'movie-app-new-a3135',
    authDomain: 'movie-app-new-a3135.firebaseapp.com',
    storageBucket: 'movie-app-new-a3135.firebasestorage.app',
    measurementId: 'G-6RK0M5B70E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDftUmE5sm0qai7QHYgCK9XzyhaXR_ls8',
    appId: '1:751281066919:android:1cfe0bbfad6edc0f6f1c82',
    messagingSenderId: '751281066919',
    projectId: 'movie-app-new-a3135',
    storageBucket: 'movie-app-new-a3135.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRiKEUms4W2zUnsks8AHmTBJcuUB3PJao',
    appId: '1:751281066919:ios:21aebbafdb9f256c6f1c82',
    messagingSenderId: '751281066919',
    projectId: 'movie-app-new-a3135',
    storageBucket: 'movie-app-new-a3135.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRiKEUms4W2zUnsks8AHmTBJcuUB3PJao',
    appId: '1:751281066919:ios:21aebbafdb9f256c6f1c82',
    messagingSenderId: '751281066919',
    projectId: 'movie-app-new-a3135',
    storageBucket: 'movie-app-new-a3135.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaKjciSfWLxD7f9IkBq-ITqyu694dI-FE',
    appId: '1:751281066919:web:1977077954a115ab6f1c82',
    messagingSenderId: '751281066919',
    projectId: 'movie-app-new-a3135',
    authDomain: 'movie-app-new-a3135.firebaseapp.com',
    storageBucket: 'movie-app-new-a3135.firebasestorage.app',
    measurementId: 'G-3V0XL1KREM',
  );
}
